print('1')
print('Estou Aprendendo Python!')
print('2')
nome='João Vítor'
idade=21
print('Olá {} ! Você tem {} anos.'.format(nome,idade))
print('3')
n1 = int(input('Digite um número '))
n2 = int(input('Digite outro número '))
print('Os números escolhidos foram {} e {}\n A soma deles é {}\n A subtração deles é {}\n A multiplicação deles é {}\n A divisão deles é {}'.format(n1,n2,n1+n2,n1-n2,n1*n2,n1/n2))
print('4')
nome1 = input('Digite seu nome ')
idade1 = int(input('Digite sua idade '))
print('Olá {} ! Você tem {} anos.'.format(nome1,idade1))
print('5')
n3 = int(input('Digite um número '))
n4 = int(input('Digite outro número '))
print('A soma de {} e {} é {}'.format(n3,n4,n3+n4))
print('6')
n5 = int(input('Digite um número '))
print ('O número escolhido foi {}\nO seu dobro é {}\nO seu triplo é {}\nA sua metade é {}'.format(n5,n5*2,n5*3,n5/2))
print('7')
real = float(input('Digite quantos reais você tem '))
print('{} reais dá {} dolares'.format(real,real/5))
print('8')
nome2 = input('Digite seu nome ')
idade2 = int(input('Digite sua idade '))
cidade = input('Digite sua cidade ')
print('Olá {} ! Você tem {} anos e mora em {}'.format(nome2,idade2,cidade))
print('Seja bem vindo a programação')
print('9')
nota1 = float(input('Digite sua nota '))
nota2 = float(input('Digite sua outra nota '))
media = (nota1 + nota2) / 2
if(media>=7.0):
    print('Aprovado')
elif(media<7 and media>=5):
    print('Recuperação')
else:
    print('Reprovado')
